# Generated by Django 6.0.3 on 2026-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to cart')], max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
